# Generated by genKlayoutStack (gks) v1.0.0
# Tech: ASAP7  Version: 1.0.0
# Source: (unknown)
# DO NOT EDIT — regenerate from TOML source
#
# Layers without physical properties are omitted from this script.
#   - label

z(input(0, 0), zstart: -300.0.nm, height: 300.0.nm, fill: 0x888888, frame: 0x444444, name: "substrate")
z(input(1, 0), zstart: -150.0.nm, height: 100.0.nm, fill: 0xaa5500, frame: 0x883300, name: "bspdn")
z(input(2, 0), zstart: 0.0.nm, height: 50.0.nm, fill: 0xffaa00, frame: 0xcc8800, name: "diffusion")
z(input(3, 0), zstart: 50.0.nm, height: 36.0.nm, fill: 0xff0000, frame: 0xcc0000, name: "poly")
z(input(4, 0), zstart: 105.0.nm, height: 45.0.nm, fill: 0xff8800, frame: 0xcc6600, name: "epi_contact")
z(input(5, 0), zstart: 105.0.nm, height: 45.0.nm, fill: 0xaa4400, frame: 0x882200, name: "gate_contact")
z(input(6, 0), zstart: 150.0.nm, height: 36.0.nm, fill: 0x0055ff, frame: 0x0033cc, name: "m0")
z(input(7, 0), zstart: 186.0.nm, height: 36.0.nm, fill: 0x00aaff, frame: 0x0088cc, name: "via0")
z(input(8, 0), zstart: 222.0.nm, height: 36.0.nm, fill: 0x0088ff, frame: 0x0066cc, name: "m1")
