#include "gks/io/ScriptWriter.hpp"

#include <algorithm>
#include <fstream>
#include <format>
#include <map>
#include <regex>
#include <set>
#include <string>
#include <vector>

namespace gks {

namespace {

// Format a double as "V.nm" — always with a decimal point
std::string fmtNm(double v) {
    std::string s = std::format("{:g}", v);
    if (s.find('.') == std::string::npos && s.find('e') == std::string::npos) {
        s += ".0";
    }
    return s + ".nm";
}

// Format a Color as "0xrrggbb" lowercase
std::string fmtColor(const Color& c) {
    return std::format("0x{:06x}", c.toInt());
}

// Parse all input(L,DT) pairs from a layer_expression string.
// Returns vector of (layer_num, datatype) pairs in order of appearance.
std::vector<std::pair<int,int>> parseInputs(const std::string& expr) {
    std::vector<std::pair<int,int>> result;
    std::regex re(R"(input\(\s*(\d+)\s*,\s*(\d+)\s*\))");
    auto begin = std::sregex_iterator(expr.begin(), expr.end(), re);
    auto end   = std::sregex_iterator();
    for (auto it = begin; it != end; ++it) {
        int ln = std::stoi((*it)[1].str());
        int dt = std::stoi((*it)[2].str());
        result.emplace_back(ln, dt);
    }
    return result;
}

} // anonymous namespace

std::expected<void, GksError> writeScript(const LayerStack& stack, const std::string& path) {
    // --- Collect layers with physical props (sort copy) ---
    std::vector<const LayerEntry*> phys_layers;
    std::vector<std::string>       skipped_names;

    for (const auto& entry : stack.layers) {
        if (entry.physical.has_value()) {
            phys_layers.push_back(&entry);
        } else {
            skipped_names.push_back(entry.name.empty() ? "(unnamed)" : entry.name);
        }
    }

    // Sort by z_start_nm ascending (stable to preserve order for ties)
    std::stable_sort(phys_layers.begin(), phys_layers.end(),
        [](const LayerEntry* a, const LayerEntry* b) {
            return a->physical->z_start_nm < b->physical->z_start_nm;
        });

    // --- Determine which (layer_num, datatype) pairs are "consumed" by zz() blocks ---
    // A layer is consumed if it appears in another layer's layer_expression (and does
    // not itself have a layer_expression).
    // Build index: (layer_num, datatype) -> LayerEntry*
    std::map<std::pair<int,int>, const LayerEntry*> layer_index;
    for (const auto* e : phys_layers) {
        layer_index[{e->layer_num, e->datatype}] = e;
    }

    // For each layer with layer_expression, mark the referenced layers as consumed
    std::set<std::pair<int,int>> consumed;
    for (const auto* e : phys_layers) {
        if (e->physical->layer_expression.has_value()) {
            auto inputs = parseInputs(*e->physical->layer_expression);
            for (auto& [ln, dt] : inputs) {
                // Only mark as consumed if the referenced layer does NOT itself have
                // a layer_expression (i.e., it is a "pure inner" layer)
                auto key = std::make_pair(ln, dt);
                if (layer_index.count(key)) {
                    const LayerEntry* ref = layer_index.at(key);
                    if (!ref->physical->layer_expression.has_value()) {
                        consumed.insert(key);
                    }
                }
            }
        }
    }

    // --- Open output file ---
    std::ofstream out(path);
    if (!out.is_open()) {
        return std::unexpected(GksError{
            std::format("writeScript: cannot open '{}' for writing", path), 0
        });
    }

    // --- Header comment ---
    out << "# Generated by genKlayoutStack (gks) v1.0.0\n";
    out << std::format("# Tech: {}  Version: {}\n", stack.tech_name, stack.version);
    out << "# Source: (unknown)\n";
    out << "# DO NOT EDIT \xe2\x80\x94 regenerate from TOML source\n";
    out << "#\n";
    if (!skipped_names.empty()) {
        out << "# Layers without physical properties are omitted from this script.\n";
        for (const auto& n : skipped_names) {
            out << "#   - " << n << "\n";
        }
    }
    out << "\n";

    // --- Emit layers ---
    for (const auto* e : phys_layers) {
        auto key = std::make_pair(e->layer_num, e->datatype);

        // Skip consumed layers (they appear inside zz() blocks)
        if (consumed.count(key) && !e->physical->layer_expression.has_value()) {
            continue;
        }

        const PhysicalProps& phys = *e->physical;

        if (phys.layer_expression.has_value()) {
            // --- zz() block ---
            // Outer line: zz(name: "...", fill: 0x..., frame: 0x...) do
            out << "zz(";
            if (!e->name.empty()) {
                out << std::format("name: \"{}\", ", e->name);
            }
            out << std::format("fill: {}, frame: {}", fmtColor(e->display.fill_color),
                                                       fmtColor(e->display.frame_color));
            out << ") do\n";

            // Inner z() calls for each input(L,DT) in the expression
            auto inputs = parseInputs(*phys.layer_expression);
            for (auto& [ln, dt] : inputs) {
                auto inner_key = std::make_pair(ln, dt);
                if (layer_index.count(inner_key)) {
                    const LayerEntry* inner = layer_index.at(inner_key);
                    const PhysicalProps& ip = *inner->physical;
                    out << std::format("  z(input({}, {}), zstart: {}, height: {})\n",
                        ln, dt, fmtNm(ip.z_start_nm), fmtNm(ip.thickness_nm));
                }
            }

            out << "end\n";
        } else {
            // --- Standard z() line ---
            out << std::format("z(input({}, {}), zstart: {}, height: {}, fill: {}, frame: {}",
                e->layer_num, e->datatype,
                fmtNm(phys.z_start_nm), fmtNm(phys.thickness_nm),
                fmtColor(e->display.fill_color),
                fmtColor(e->display.frame_color));
            if (!e->name.empty()) {
                out << std::format(", name: \"{}\"", e->name);
            }
            out << ")\n";
        }
    }

    if (!out.good()) {
        return std::unexpected(GksError{
            std::format("writeScript: write error on '{}'", path), 0
        });
    }

    return {};
}

} // namespace gks
